apiVersion: v1
kind: Service
metadata:
  name: hms-backend-svc
spec:
  selector:
    app: hms-backend
  ports:
    - port: 8081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hms-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hms-backend
  template:
    metadata:
      labels:
        app: hms-backend
    spec:
      containers:
        - name: hms-backend
          image: aadhireddy/property-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/propertydb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: rootpassword
          ports:
            - containerPort: 8080
